  /*************************/
 /*  BMW BIKE PARTS DATA  */
/*************************/ 

var BMW_parts = [
    //Part A09020
    {  
        partNum: 'A09020',
        partName: 'Bash plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y86f4qpb',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 2260,
    },
    //Part A09025
    {  
        partNum: 'A090025',
        partName: 'Bash plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8ecotqe',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 45,
        price: 2295 ,
    },
    //Part A09040
    {  
        partNum: 'A09040',
        partName: 'Spot Light Kit(under Beak fitment)',
        partDesc: 'Spot light Kit',
        models: ['F650GS','F700GS','F800GS','F800GSA','Also fits Pre F800GS pre face lift'],
        imgLink: 'http://tinyurl.com/y8lswq57',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 2900,
    },
    //Part A09041
    {  
        partNum: 'A09041',
        partName: 'Spot Lihgt Bracket(under Beak fitment)',
        partDesc: 'Manufactured from aluminium and comes with securing kit',
        models: ['F650GS','F700GS','F800GS','F800GSA','Also fits Pre F800GS pre face lift'],
        imgLink: 'http://tinyurl.com/y8q3q4fd',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 60,
        price: 778,
    },
    //Part A09055
    {  
        partNum: 'A09055',
        partName: 'Rear brake lever extension',
        partDesc: 'Extension of rear brake lever easier to access',
        models: ['F650GS','F700GS','F800GS','F8000GSA'],
        imgLink: 'http://tinyurl.com/y6vunjxz',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 245,
    },
    //Part A09060
    {  
        partNum: 'A09060',
        partName: 'Luggage Touring Plate',
        partDesc: 'Manufactured from aluminium for light weight secures soft luggage with straps',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9d9kqnr',
        colors: 'Black',
        grnt: '1 Year',
        instTime:30,
        price: 995,
    },

//Part A09077
    {  
        partNum: 'A09077',
        partName: 'Wide Pillion Foot Peg',
        partDesc: 'Made from Stainless steel corrosive resist and has more foot surface',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y7xhzzr8',
        colors: 'Stainless Steel',
        grnt: '1 Year',
        instTime: 30,
        price: 940,
    },
    //Part A09078
    {  
        partNum: 'A09078',
        partName: 'Wide Pillion',
        partDesc: 'Made from Stainless steel corrosive resist and has more foot surface',
        models:['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycv3txso',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 975,
    },
    //Part A09080
    {  
        partNum: 'A09080',
        partName: 'Bash Plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8mkszs3',
        colors: 'Aliminium',
        grnt: '1 year',
        instTime: 45,
        price: 2020,
    },
    //Part A09085
    {  
        partNum: 'A09085',
        partName: 'Bash Plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yaocnyoy',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 45,
        price: 2065,
    },
    //Part A09088
    {  
        partNum: 'A09088',
        partName: 'Radiator protector',
        partDesc: 'Manufactured in aluminium protects radiator from loose projectiles on the road and is a must for off riding off road',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yd7eks67',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 60,
        price: 865,
    },
    //Part A09089P
    {  
        partNum: 'A09089P',
        partName: 'Head Light Guard SS Grid Type Dzus Connectors',
        partDesc: 'Manufactured from aluminium and has stainless steel arms protects the Head Light from loose projectile and is a must for off road riding',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yc63tlg8',
        colors: 'Silver',
        grnt: '1 year',
        instTime: 45,
        price: 952,
    },
    //Part A09090
    {  
        partNum: 'A09090',
        partName: 'Head Light Guard with Polycarp Lens',
        partDesc: 'Frame is made from aluminium and has stainless steel arms, glass is Polycarp to protects the head light from loose projectile as well as stone chips and is a must for off road riding',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ybnw9596',
        colors: 'Black and Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 740,
    },
    //Part A09091
    {  
        partNum: 'A09091',
        partName: 'Ornge clip on lens',
        partDesc: 'Ornge lens that clips onto the Head Light guard for day time riding',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ybhgmmta',
        colors: 'Orange',
        grnt: '0',
        instTime: 5,
        price: 595,
    },
    //Part A09092
    {  
        partNum: 'A09092',
        partName: 'Rear brake reservoir protector',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycnyc6kl',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 375,
    },
    //Part A09095
    {  
        partNum: 'A09095',
        partName: 'Front Brake reservoir protector',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GS(pre 2012'],
        imgLink: 'http://tinyurl.com/yc62zpdj',
        colors: 'Black or Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 375,
    },
    //Part A09096
    {  
        partNum: 'A09096',
        partName: 'Front Brake reservoir protector 3mm Aliminuim anodized',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8uajevf',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 420,
    },
    //Part A09097
    {  
        partNum: 'A09097',
        partName: 'Front Brake reservoir protector 3mm Aliminuim Powder Coated Black',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9wdjoff',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 420,
    },
    //Part A09098
    {  
        partNum: 'A09098',
        partName: 'Rear Brake Lever Extension',
        partDesc: 'Manufactured from aluminium easy access to brake lever especially in an emergency',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yc668vfh',
        colors: 'Siver',
        grnt: '1 Year',
        instTime: 15,
        price: 245,
    },
    //Part A09100
    {  
        partNum: 'A09100',
        partName: 'Spot Light Brackets set 08-11',
        partDesc: 'Secures spot Lights',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'https://2mju3q-am3pap001.files.1drv.com/y4mcsqz8Str6tnIm2dP5mHCSGIlrnD8dAV2nXSv_WKtLSoUU15qCgKw8FIfjIZS_WvXNEhYAbk19l934UaGFQdsJCJtidkPaj9uXNqL4SkZk8LgasjZoYHF3IC4Ii1kRHNys7Pr44EuOpY0wcD01rJCOl_K-1VXqakKHzdF1X8Tzy0mUxYMdITDouGBM9xyrK0ZLvZ7DOGDwP73EmIQB0YPA37PdXzPV3bLz0uTTrB8zzM?width=213&height=220&cropmode=none',
        colors: 'Black',
        grnt: '1 year',
        instTime: 30,
        price: 625,
    },
    //Part A09102
    {  
        partNum: 'A09102',
        partName: 'Spot Light Bracket(2012)',
        partDesc: 'Secures spot Lights',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yb7mwola',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 625,
    },
    //Part A09105
    {  
        partNum: 'A09105',
        partName: 'Spot Light Wiring Kit-(55W H3 Bulbs',
        partDesc: 'Kit',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y7js9tkf',
        colors: '0',
        grnt: '1 Year',
        instTime: 60,
        price: 2020,
    },
    //Part A09106
    {  
        partNum: 'A09106',
        partName: 'Spot Light Wiring Kit-LED Lights(10W 900nLumens)',
        partDesc: 'Wiring Kit, Brackets(A9100), Swich and Wiring',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8tega6c',
        colors: '0',
        grnt: '0',
        instTime: 60,
        price: 2900,
    },
    //Part A09108
    {  
        partNum: 'A09108',
        partName: 'Spot Light Wiring Kit-LED Lights(10W 900nLumens)',
        partDesc: 'Wiring Kit, Brackets(A9102), Swich and Wiring',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycrsae9r',
        colors: '0',
        grnt: '0',
        instTime: 60,
        price: 2900,
    },
    //Part A09110
    {  
        partNum: 'A09110',
        partName: 'Wide Side Stand Extender',
        partDesc: 'Manufactured from aluminium with a rubber foot pad helps with non slip',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y7ys5hjz',
        colors: 'Silver and Black',
        grnt: '1 Year',
        instTime: 20,
        price: 305,
    },
    //Part A09115
    {  
        partNum: 'A09115',
        partName: 'Crash Bar Set-Black powder coated',
        partDesc: 'Help prevent scratches and engine damage when bike has fallen over, can prevent rider to a certain extent from getting injured. ',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9tjkxjv',
        colors: 'Black',
        grnt: '1 year',
        instTime: 90,
        price: 2235,
    },
    //Part A09117
    {  
        partNum: 'A09117',
        partName: 'Upper crash bar set-stainless steel',
        partDesc: 'Mounts to original set of crash bars with support brackets to the main frame',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y7qnon4k',
        colors: 'Silve',
        grnt: '1 Year',
        instTime: 90,
        price: 1985,
    },
    //Part A09120
    {  
        partNum: 'A09120',
        partName: 'Soft luggage touring Bracket',
        partDesc: 'Manufactured from aluminium, secures soft luggage with straps and comes with securing kit',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycq8gvao',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 995,
    },
    //Part A09122
    {  
        partNum: 'A09122',
        partName: 'Stoft Luggage Tourng Bracket',
        partDesc: 'Stoft Luggage Tourng Bracket for BMW Bag and comes with securing kit',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9xzd2qr',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 995,
    },
    //Part A09125
    {  
        partNum: 'A09125',
        partName: 'Handlebar Raisers',
        partDesc: 'Lifts the Handle bars into a more comfortable sitting position',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y77mb7fq',
        colors: '0',
        grnt: '1 Year',
        instTime: 45,
        price: 615,
    },
    //Part A09127
    {  
        partNum: 'A09127',
        partName: 'Handlebar Raisers',
        partDesc: 'Lifts the Handle bars into a more comfortable sitting position',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ybxqut4r',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 615,
    },
    //Part A09128
    {  
        partNum: 'A09128',
        partName: 'Two Finger Brake Lever',
        partDesc: 'Manufactured from aluminium and is more effective than the standard lever',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yd8oodb2',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 995,
    },
   //Part A09129
    {  
        partNum: '019129',
        partName: 'Two Finger Brake Lever',
        partDesc: 'Manufactured from aluminium and is more effective than the standard lever',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yd9lr4qr',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 995,
    },
     //Part A09137
    {  
        partNum: 'A09137',
        partName: 'Led Spot Light Protector',
        partDesc: 'Encases the Led lights protects them from damages if the bike falls over',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8u2dprm',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 490,
    },
    //Part A11115
    {  
        partNum: 'A11115',
        partName: 'Top Box Bracket',
        partDesc: 'Manufactured from aluminium, secure the top box to top of rear mudguard even in off road conditions',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9xvbggc',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 735,
    },
    //Part A11550
    {  
        partNum: 'A11550',
        partName: 'Right Side Pannier Aluminium',
        partDesc: 'Manufactured from aluminium 405X455X285 and can lock',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y882ub4x',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4370,
    }

]
