  /*************************/
 /*  BMW BIKE PARTS DATA  */
/*************************/ 

var BMW_parts = [
    //Part A09020
    {  
        partNum: 'A09020',
        partName: 'Bash plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y86f4qpb',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 2260,
    },
    //Part A09025
    {  
        partNum: 'A090025',
        partName: 'Bash plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8ecotqe',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 45,
        price: 2295 ,
    },
    //Part A09040
    {  
        partNum: 'A09040',
        partName: 'Spot Light Kit(under Beak fitment)',
        partDesc: 'Spot light Kit',
        models: ['F650GS','F700GS','F800GS','F800GSA','Also fits Pre F800GS pre face lift'],
        imgLink: 'http://tinyurl.com/y8lswq57',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 2900,
    },
    //Part A09041
    {  
        partNum: 'A09041',
        partName: 'Spot Lihgt Bracket(under Beak fitment)',
        partDesc: 'Manufactured from aluminium and comes with securing kit',
        models: ['F650GS','F700GS','F800GS','F800GSA','Also fits Pre F800GS pre face lift'],
        imgLink: 'http://tinyurl.com/y8q3q4fd',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 60,
        price: 778,
    },
    //Part A09055
    {  
        partNum: 'A09055',
        partName: 'Rear brake lever extension',
        partDesc: 'Extension of rear brake lever easier to access',
        models: ['F650GS','F700GS','F800GS','F8000GSA'],
        imgLink: 'http://tinyurl.com/y6vunjxz',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 245,
    },
    //Part A09060
    {  
        partNum: 'A09060',
        partName: 'Luggage Touring Plate',
        partDesc: 'Manufactured from aluminium for light weight secures soft luggage with straps',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9d9kqnr',
        colors: 'Black',
        grnt: '1 Year',
        instTime:30,
        price: 995,
    },

//Part A09077
    {  
        partNum: 'A09077',
        partName: 'Wide Pillion Foot Peg',
        partDesc: 'Made from Stainless steel corrosive resist and has more foot surface',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y7xhzzr8',
        colors: 'Stainless Steel',
        grnt: '1 Year',
        instTime: 30,
        price: 940,
    },
    //Part A09078
    {  
        partNum: 'A09078',
        partName: 'Wide Pillion',
        partDesc: 'Made from Stainless steel corrosive resist and has more foot surface',
        models:['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycv3txso',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 975,
    },
    //Part A09080
    {  
        partNum: 'A09080',
        partName: 'Bash Plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8mkszs3',
        colors: 'Aliminium',
        grnt: '1 year',
        instTime: 45,
        price: 2020,
    },
    //Part A09085
    {  
        partNum: 'A09085',
        partName: 'Bash Plate',
        partDesc: 'Made off aliminuim. Protects the engine casing from lose protectiles and road hazards must have for off roading',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yaocnyoy',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 45,
        price: 2065,
    },
    //Part A09088
    {  
        partNum: 'A09088',
        partName: 'Radiator protector',
        partDesc: 'Manufactured in aluminium protects radiator from loose projectiles on the road and is a must for off riding off road',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yd7eks67',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 60,
        price: 865,
    },
    //Part A09089P
    {  
        partNum: 'A09089P',
        partName: 'Head Light Guard SS Grid Type Dzus Connectors',
        partDesc: 'Manufactured from aluminium and has stainless steel arms protects the Head Light from loose projectile and is a must for off road riding',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yc63tlg8',
        colors: 'Silver',
        grnt: '1 year',
        instTime: 45,
        price: 952,
    },
    //Part A09090
    {  
        partNum: 'A09090',
        partName: 'Head Light Guard with Polycarp Lens',
        partDesc: 'Frame is made from aluminium and has stainless steel arms, glass is Polycarp to protects the head light from loose projectile as well as stone chips and is a must for off road riding',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ybnw9596',
        colors: 'Black and Silver',
        grnt: '1 Year',
        instTime: 45,
        price: 740,
    },
// //Part A09091
    {  
        partNum: 'A09091',
        partName: 'Ornge clip on lens',
        partDesc: 'Ornge lens that clips onto the Head Light guard for day time riding',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ybhgmmta',
        colors: 'Orange',
        grnt: '0',
        instTime: 5,
        price: 595,
    },
    //Part A09092
    {  
        partNum: 'A09092',
        partName: 'Rear brake reservoir protector',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycnyc6kl',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 375,
    },
    //Part A09095
    {  
        partNum: 'A09095',
        partName: 'Front Brake reservoir protector',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GS(pre 2012'],
        imgLink: 'http://tinyurl.com/yc62zpdj',
        colors: 'Black or Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 375,
    },
    //Part A09096
    {  
        partNum: 'A09096',
        partName: 'Front Brake reservoir protector 3mm Aliminuim anodized',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y8uajevf',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 420,
    },
    //Part A09097
    {  
        partNum: 'A09097',
        partName: 'Front Brake reservoir protector 3mm Aliminuim Powder Coated Black',
        partDesc: 'Manufactured from aluminium, protects the reservoir from damage due to loose projectiles and road hazards',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y9wdjoff',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 420,
    },
    //Part A09098
    {  
        partNum: 'A09098',
        partName: 'Rear Brake Lever Extension',
        partDesc: 'Manufactured from aluminium  easy access to brake lever especially in an emergency',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yc668vfh',
        colors: 'Siver',
        grnt: '1 Year',
        instTime: 15,
        price: 245,
    },