  /****************************/
 /*  TOP BOXES AND PANNIERS  */
/****************************/

var TopBoxPannier = [
    //Part A08400     
    {
        partNum: 'A08400',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium and has 41 litre volumetric capacity and requires a A11155 Top Plate to mount onto the bike',
        models: ['KTM 1290 Adventure'],
        imgLink: 'http://tinyurl.com/y8t9ulwu',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB'
    },
    //Part A11110
    {  
        partNum: 'A11110',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['BMW R1200GS/R1200GS Adventure'],
        imgLink: 'http://tinyurl.com/y7fts7tc',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB'
    },
    //Part A11111
    {  
        partNum: 'A11111',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['BMW R1200GS/R1200GS Adventure'],
        imgLink: 'http://tinyurl.com/y8v4rhqe',
        colors: 'New Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4040,
        cat: 'TB', 
    },
    //Part A11112
    {  
        partNum: 'A11112',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['BMW R1200GS/R1200GS Adventure'],
        imgLink: 'http://tinyurl.com/y9ltemvy',
        colors: 'New Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4150,
        cat: 'TB', 
    },
    //Part A11232
    {  
        partNum: 'A11232',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT1200Z Super Tenere'],
        imgLink: 'http://tinyurl.com/ybn6cnaa',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB', 
    },
    //Part A11234
    {  
        partNum: 'A11234',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT1200Z Super Tenere'],
        imgLink: 'http://tinyurl.com/ybgke3n8',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4040,
        cat: 'TB', 
    },
    //Part A11236
    {  
        partNum: 'A11236',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT1200Z Super Tenere'],
        imgLink: 'http://tinyurl.com/yb9ur576',
        colors: 'Silver',
        grnt: '1 year',
        instTime: 30,
        price: 4150,
        cat: 'TB', 
    },
    //Part A11242
    {  
        partNum: 'A11242',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT660Z Tenere'],
        imgLink: 'http://tinyurl.com/ybcnywc4',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB', 
    },
    //Part A11246
    {  
        partNum: 'A11246',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity and powder coated black',
        models: ['Yamaha XT660Z Tenere'],
        imgLink: 'http://tinyurl.com/yb4secyp',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 4040,
        cat: 'TB', 
    },
    //Part A11248
    {  
        partNum: 'A11248',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT660Z Tenere'],
        imgLink: 'http://tinyurl.com/ybsap4vz',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4150,
        cat: 'TB', 
    },
    //Part A11500
    {  
        partNum: 'A11500',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium with side latch no top plate required',
        models: ['BMW R1200GS Adventuer K51'],
        imgLink: 'http://tinyurl.com/y8x5s4a8',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4290,
        cat: 'TB', 
    },
    //Part A11501
    {  
        partNum: 'A11501',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium (W)394mm X (B)324mm X (H)228mm (Half loaf 28 Ltr)',
        models: ['BMW R1200GS'],
        imgLink: 'http://tinyurl.com/yc7z9b6x',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 10,
        price: 3960,
        cat: 'TB', 
    },
    //Part A11502
    {  
        partNum: 'A11502',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium with side latch no top plate required, powder coated black, no plate required',
        models: ['BMW R1200GS Adventuer K51'],
        imgLink: 'http://tinyurl.com/yakw9ffq',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 10,
        price: 4350,
        cat: 'TB', 
    },
    //Part A11248
    {  
        partNum: 'A11505',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium with side latch no top plate required, powder coated new silver, no plate required',
        models: ['BMW R1200GS Adventuer K51'],
        imgLink: 'http://tinyurl.com/y8w5p6e5',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 10,
        price: 4390,
        cat: 'TB', 
    },
    //Part A19000
    {  
        partNum: 'A19000',
        partName: 'Pannier and Top Box strap',
        partDesc: 'Secures the lids of the Top Boxes and Panniers from coming open while riding',
        models: ['BMW KTM and Yamaha'],
        imgLink: 'http://tinyurl.com/y7dtjgwb',
        colors: '0',
        grnt: '0',
        instTime: 0,
        price: 235,
        cat: 'TB', 
    },
    //Part A19010
    {  
        partNum: 'A19010',
        partName: 'Top Box Back Rest Pad',
        partDesc: 'Pad secured to the top box so passenger can sit comfortable',
        models: ['BMW KTM and Yamaha'],
        imgLink: 'http://tinyurl.com/ybool5ll',
        colors: 'Black',
        grnt: '0',
        instTime: 15,
        price: 795,
        cat: 'TB', 
    },
    //Part A11150
    {  
        partNum: 'A11150',
        partName: 'Top Box Bracket',
        partDesc: 'Made from aluminium and is used to mount top box above rear mud guard. Can be used in off road conditions. ',
        models: ['KTM 1190'],
        imgLink: 'http://tinyurl.com/ycj2l37v',
        colors: 'Aluminium',
        grnt: '1 Year',
        instTime: 30 ,
        price: 755 ,
        cat:''
    },
    //Part A11140
    {  
        partNum: 'A11140',
        partName: 'Top Box Bracket Adventure',
        partDesc: 'Manufactured from aliminuim, secures the top even off roading',
        models: ['KTM 950','KTM 990',''],
        imgLink: 'http://tinyurl.com/y7w5o2yo',
        colors: 'Silver',
        grnt: '!1 Year',
        instTime: 30,
        price: 735,
    },
    //Part A11550
    {  
        partNum: 'A11550',
        partName: 'Right Side Pannier Aluminium',
        partDesc: 'Manufactured from aluminium 405X455X285 and can lock',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y882ub4x',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4370,
    },
    //Part A11560
    {  
        partNum: 'A11560',
        partName: 'Left Side Pannier Aluminium',
        partDesc: 'Manufactured from aluminium 405X455X285 and can lock',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ybhrc8rp',
        colors: 'Siver',
        grnt: '1 Year',
        instTime: 30,
        price: 4370,
    },
    //Part A01460
    {  
        partNum: 'A01460',
        partName: 'Pannnier and Top Box Lid Strap Assembly',
        partDesc: 'Straps to secure Panniers and Top Boxes',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yazs8tw2',
        colors: 'Black',
        grnt: '0',
        instTime: 0,
        price: 235,
    },
        //Part A190105
    {  
        partNum: 'A190100',
        partName: 'Single Pocket inner Pannier Bag',
        partDesc: 'Inner lining for pannier to protect and keep inside of pannier clean  ',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yb23po6o',
        colors: 'Black and Orange',
        grnt: '0',
        instTime: 0,
        price: 540,
    },
    //Part A190105
    {  
        partNum: 'A190105',
        partName: 'Multi Pocket Inner Pannier Bag ',
        partDesc: 'Multi pocket bag to keep items organized, clean and protects the inside of the Pannier',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/y7gsxqqo',
        colors: 'Black and Orange',
        grnt: '0',
        instTime: 0,
        price: 600,

    },
    //Part A190110
    {  
        partNum: 'A190110',
        partName: 'Pannier Inner Bag Exhaust Side',
        partDesc: 'Inner lining for pannier to protect and keep inside of pannier clean',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/yd7d4bzt',
        colors: 'Black and Orange',
        grnt: '0',
        instTime: 0,
        price: 540,
    },
        //Part A190145
    {  
        partNum: 'A190145',
        partName: 'Pannier Lid Organizer',
        partDesc: 'To carry small items in the lid of the pannier and kept organised',
        models: ['F650GS','F700GS','F800GS','F800GSA'],
        imgLink: 'http://tinyurl.com/ycvxcspj',
        colors: 'Black and Orange',
        grnt: '0',
        instTime: 0,
        price: 525,
    },
]