  /****************************/
 /*  TOP BOXES AND PANNIERS  */
/****************************/

var TopBoxPannier = [
    //Part A08400     
    {
        partNum: 'A08400',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium and has 41 litre volumetric capacity and requires a A11155 Top Plate to mount onto the bike',
        models: ['KTM 1290 Adventure'],
        imgLink: 'http://tinyurl.com/y8t9ulwu',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB'
    },
    //Part A11110
    {  
        partNum: 'A11110',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity .',
        models: ['BMW R1200GS/R1200GS Adventure'],
        imgLink: 'http://tinyurl.com/y7fts7tc',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB'
    },
    //Part A11111
    {  
        partNum: 'A11111',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['BMW R1200GS/R1200GS Adventure'],
        imgLink: 'http://tinyurl.com/y8v4rhqe',
        colors: 'New Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4040,
        cat: 'TB', 
    },
    //Part A11112
    {  
        partNum: 'A11112',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['BMW R1200GS/R1200GS Adventure'],
        imgLink: 'http://tinyurl.com/y9ltemvy',
        colors: 'New Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4150,
        cat: 'TB', 
    },
    //Part A11232
    {  
        partNum: 'A11232',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT1200Z Super Tenere'],
        imgLink: 'http://tinyurl.com/ybn6cnaa',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB', 
    },
    //Part A11234
    {  
        partNum: 'A11234',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT1200Z Super Tenere'],
        imgLink: 'http://tinyurl.com/ybgke3n8',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4040,
        cat: 'TB', 
    },
    //Part A11236
    {  
        partNum: 'A11236',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT1200Z Super Tenere'],
        imgLink: 'http://tinyurl.com/yb9ur576',
        colors: 'Silver',
        grnt: '1 year',
        instTime: 30,
        price: 4150,
        cat: 'TB', 
    },
    //Part A11242
    {  
        partNum: 'A11242',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT660Z Tenere'],
        imgLink: 'http://tinyurl.com/ybcnywc4',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 3930,
        cat: 'TB', 
    },
    //Part A11246
    {  
        partNum: 'A11246',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity and powder coated black',
        models: ['Yamaha XT660Z Tenere'],
        imgLink: 'http://tinyurl.com/yb4secyp',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 30,
        price: 4040,
        cat: 'TB', 
    },
    //Part A11248
    {  
        partNum: 'A11248',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium walls with stainless and has 41 litre volumetric capacity',
        models: ['Yamaha XT660Z Tenere'],
        imgLink: 'http://tinyurl.com/ybsap4vz',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4150,
        cat: 'TB', 
    },
    //Part A11500
    {  
        partNum: 'A11500',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium with side latch no top plate required',
        models: ['BMW R1200GS Adventuer K51'],
        imgLink: 'http://tinyurl.com/y8x5s4a8',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 30,
        price: 4290,
        cat: 'TB', 
    } ,
    //Part A11501
    {  
        partNum: 'A11501',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium (W)394mm X (B)324mm X (H)228mm (Half loaf 28 Ltr)',
        models: ['BMW R1200GS'],
        imgLink: 'http://tinyurl.com/yc7z9b6x',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 10,
        price: 3960,
        cat: 'TB', 
    },
    //Part A11502
    {  
        partNum: 'A11502',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium with side latch no top plate required, powder coated black, no plate required',
        models: ['BMW R1200GS Adventuer K51'],
        imgLink: 'http://tinyurl.com/yakw9ffq',
        colors: 'Black',
        grnt: '1 Year',
        instTime: 10,
        price: 4350,
        cat: 'TB', 
    
    },
    //Part A11505
    {  
        partNum: 'A11505',
        partName: 'Top Box',
        partDesc: 'Manufactured from 2 mm aluminium with side latch no top plate required, powder coated new silver, no plate required',
        models: ['BMW R1200GS Adventuer K51'],
        imgLink: 'http://tinyurl.com/y8w5p6e5',
        colors: 'Silver',
        grnt: '1 Year',
        instTime: 10,
        price: 4390,
        cat: TB, 
    },   
       //Part A19000
    {  
        partNum: 'A19000',
        partName: 'Pannier and Top Box strap',
        partDesc: 'Secures the lids of the Top Boxes and Panniers from coming open while riding',
        models: ['BMW KTM and Yamaha'],
        imgLink: 'http://tinyurl.com/y7dtjgwb',
        colors: '0',
        grnt: '0',
        instTime: 0,
        price: 235,
        cat: 'TB', 
    },
       //Part A19010
    {  
        partNum: 'A19010',
        partName: 'Top Box Back Rest Pad',
        partDesc: 'Pad secured to the top box so passenger can sit comfortable',
        models: ['BMW KTM and Yamaha'],
        imgLink: 'http://tinyurl.com/ybool5ll',
        colors: 'Black',
        grnt: '0',
        instTime: 15,
        price: 795,
        cat: 'TB', 
    }     
]